import type { Metadata } from 'next';
import './globals.css';
import StoreProvider from '@/components/providers/store.provider';
import { Toaster } from '@/components/ui/sonner';
import { Bebas_Neue, Inter } from 'next/font/google';
import { GoogleOAuthProvider } from '@react-oauth/google';

const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bebas-neue',
});

const inter = Inter({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'TokoPakBimo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${inter.variable}`}>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ''}
          locale="en"
        >
          <StoreProvider>{children}</StoreProvider>
        </GoogleOAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
